### ISSUE TITLE
ِAdmin page to add,list and remove

### ISSUE THREAD

**Issue by Yousifff** [Yousifff/service_controller#6] opened 2024-02-20 18:40 UTC
Currently testing add,list and remove servers

**Comment by Zaubeerer** [comment] 2024-02-22 16:18
Closing as it was solved in https://github.com/Yousifff/service_controller/pull/4

**Comment by Zaubeerer** [comment] 2024-02-22 16:19
Closing as duplicate of #7

**Closed as completed** 2024-02-22 16:29 UTC
